apiVersion: v1
appVersion: [[ .AppVersion ]]
description: A Helm chart for kiam-watchdog
engine: gotpl
home: https://github.com/giantswarm/kiam-watchdog
icon: https://s.giantswarm.io/app-icons/1/png/default-app-light.png
name: kiam-watchdog
sources:
- https://github.com/giantswarm/kiam-watchdog
version: [[ .Version ]]
annotations:
  application.giantswarm.io/team: "phoenix"
